version: '3.9'
services:

  jenkins:
    container_name: jenkins_container
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./docker-volumes/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  jenkins-agent:
    container_name: jenkins_agent_container
    image: jenkins/ssh-agent:jdk11
    privileged: true
    user: root
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDVsDpVcxyhb3q9oRz2OthPzTJYuu8v1tEew/Iu1mgUgpLYc1+FPQyrsIDE30JYsyWJ9x/iy5b+105ef80S0G6GtCOST+OR1X7l8F6BodvT/nLT61Rgh0qdaJw5knR+qIv27x7yqsMPeNoSh2OiRSo8YNkzy4fUXclGFmU2eYseyQ8d2x5cuOTi9Wvd12i3r8aMiPk6SqETf1rsaQ7u+DX/Lc3lGuU69UwfZby+siiiksVbPu3DJtNsVXpNDphI+kII3b2HSeVoiJaVGcg1ouH2BNGdFHAYE+gLL+I2yTZZh9AIyVno/XpUR0XB4iEd5hFTmw4OaLxNqi62RDPqQxVywURqxbJgIw4sFrwHcOR5mttw+/HpG4PL8xh9RDkSErsAf6ONmw71PtO14F4acFOh3GnCOPEXx+jafXOLmQLuTrlJNbOL+bACx7xNk8cOcbch+9SfBYte+bFbTjvRRR/e+Ulqb+CtVYanwBqkuNlQ2GHMr/kZoVf/WhzB2YM5+f8= root@devops-HP-Laptop-15-dw3xxx

#  redis:
#    container_name: redis_container
#    image: redis:alpine
#    restart: always
#    ports:
#      - '6379:6379'
#    command: redis-server --loglevel warning
#    volumes:
#      - ./docker-volumes/cache:/data
# #
#  redis-commander:
#    container_name: redis-commander
#    image: ghcr.io/joeferner/redis-commander:latest
#    restart: always
#    ports:
#      - '8081:8081'
#    environment:
#    - REDIS_HOSTS=local:redis_container:6379
#
#  mongodb:
#    container_name: mongodb_container
#    image: mongo:latest
#    restart: always
#    ports:
#      - 27017:27017
#    volumes:
#      - ./docker-volumes/data:/data/db
#
#
#  mysql:
#    image: mysql:latest
#    container_name: mysql_container
#    ports:
#      - "3306:3306"
#    restart: always
#    environment:
#      - MYSQL_ROOT_PASSWORD=api
#      - MYSQL_USER=jobber
#      - MYSQL_DATABASE=jobber_auth
#      - MYSQL_PASSWORD=api
#    volumes:
#      - ./docker-volumes/mysql:/var/lib/mysql 
#
#
#
#  postgres:
#    container_name: postgres_container
#    image: postgres
#    restart: always
#    environment:
#      - POSTGRES_USER=jobber
#      - POSTGRES_PASSWORD=api
#      - POSTGRES_DB=jobber_reviews
#    ports:
#      - '5432:5432'
#    volumes:
#      - ./docker-volumes/postgres:/var/lib/postgresql
#
#  rabbitmq:
#    container_name: rabbitmq_container
#    image: rabbitmq:3.13-rc-management-alpine
#    restart: always
#    environment:
#      - RABBITMQ_DEFAULT_USER=jobber
#      - RABBITMQ_DEFAULT_PASS=jobberpass
#    ports:
#      # AMQP protocol port
#      - '5672:5672'
#      # Management UI
#      - '15672:15672'
#
#  elasticsearch:
#    container_name: elasticsearch_container
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
#    restart: always
#    user: "1000:1000"
#    environment: ['CLI_JAVA_OPTS=-Xms2g -Xmx2g','bootstrap.memory_lock=true','discovery.type=single-node','xpack.security.enabled=false', 'xpack.security.enrollment.enabled=false',  'ELASTIC_PASSWORD=admin1234']
#    ports:
#      - 9200:9200
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#      nofile:
#        soft: 65536
#        hard: 65536
#    deploy:
#      resources:
#          limits:
#            cpus: '2.0'
#          reservations:
#            cpus: '1.0'
#    volumes:
#      - ./docker-volumes/elasticsearch-data:/usr/share/elasticsearch/data
#
#
##  kibana:
##    container_name: kibana_container
##    image: docker.elastic.co/kibana/kibana:8.12.0
##    restart: always
##    environment:
##      - ELASTICSEARCH_HOSTS=["http://elasticsearch_container:9200"]
##      - ELASTICSEARCH_USERNAME=kibana_system
##      - ELASTICSEARCH_PASSWORD=kibana
##      - ELASTICSEARCH_SERVICEACCOUNT_TOKEN=AAEAAWVsYXN0aWMva2liYW5hL2pvYmJlci1raWJhbmE6N3BWZ0ItZWxSY21wMEJ0Y3ZKNTlHZw
##      - XPACK_FLEET_AGENTS_ELASTICSEARCH_HOSTS=["http://elasticsearch_container:9200"]
##    ports:
##      - 5601:5601
##    networks:
##      - elastic
##    volumes:
##      - ./kibana.yml/:/usr/share/kibana/config/kibana.yml:ro
##    depends_on: 
##      - elasticsearch
##
#
#
#  gateway:
#    container_name: gateway_container
#    build:
#      context: ../microservices/1-gateway-service
#      dockerfile: Dockerfile
#    restart: always
#    ports:
#      - 4000:4000
#    env_file: ../microservices/1-gateway-service/.env
#    environment:
#        - ENABLE_APM=1
#        - GATEWAY_JWT_TOKEN=1282722b942e08c8a6cb033aa6ce850e
#        - JWT_TOKEN=8db8f85991bb28f45ac0107f2a1b349c
#        - NODE_ENV=development
#        - SECRET_KEY_ONE=032c5c3cfc37938ae6dd43d3a3ec7834
#        - SECRET_KEY_TWO=d66e377018c0bc0b5772bbc9b131e6d9
#        - CLIENT_URL=http://localhost:3000
#        - AUTH_BASE_URL=http://auth_container:4002
#        - USERS_BASE_URL=http://localhost:4003
#        - GIG_BASE_URL=http://localhost:4004
#        - MESSAGE_BASE_URL=http://chat_container:4005
#        - ORDER_BASE_URL=http://order_container:4006
#        - REVIEW_BASE_URL=http://localhost:4007
#        - REDIS_HOST=redis://redis_container:6379
#        - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
#        - ELASTIC_APM_SERVER_URL=http://apm_server_container:8200
#        - ELASTIC_APM_SECRET_TOKEN=
#    depends_on:
#      - elasticsearch
#  
#  chat:
#    container_name: chat_container
#    build:
#      context: ../microservices/6-chat-service
#      dockerfile: Dockerfile
#    restart: always
#    ports:
#      - 4005:4005
#    env_file: ../microservices/6-chat-service/.env
#    environment:
#      - ENABLE_APM=1
#      - DATABASE_URL=mongodb://mongodb_container:27017/jobber-chat
#      - GATEWAY_JWT_TOKEN=1282722b942e08c8a6cb033aa6ce850e
#      - JWT_TOKEN=8db8f85991bb28f45ac0107f2a1b349c
#      - NODE_ENV=development
#      - AP_GATEWAY_URL=http://gateway_container:4000
#      - RABBITMQ_ENDPOINT=amqp://jobber:jobberpass@rabbitmq_container:5672
#      - CLOUD_NAME=dyamr9ym3
#      - CLOUD_API_KEY=385269193982147
#      - CLOUD_API_SECRET=-h9hU43QMy68AcIaMyP0ULKbibI
#      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
#      - ELASTIC_APM_SERVER_URL=http://apm_server_container:8200
#      - ELASTIC_APM_SECRET_TOKEN=
#    depends_on:
#      - elasticsearch
#      - mongodb
#  
#  order:
#    container_name: order_container
#    build:
#      context: ../microservices/7-order-service
#      dockerfile: Dockerfile
#    restart: always
#    ports:
#      - 4006:4006
#    env_file: ../microservices/7-order-service/.env
#    environment:
#      - ENABLE_APM=1
#      - DATABASE_URL=mongodb://mongodb_container:27017/jobber-chat
#      - GATEWAY_JWT_TOKEN=1282722b942e08c8a6cb033aa6ce850e
#      - JWT_TOKEN=8db8f85991bb28f45ac0107f2a1b349c
#      - NODE_ENV=development
#      - AP_GATEWAY_URL=http://gateway_container:4000
#      - CLIENT_URL=http://localhost:3000
#      - RABBITMQ_ENDPOINT=amqp://jobber:jobberpass@rabbitmq_container:5672
#      - STRIPE_API_KEY=sk_test_51OAXs6DTglvMeJPrlX1Lp9Mw7aXwlBbFJOLQdlkFv5mRKPkQdFrxvYN68xZ54wBr6VbP44khSM5UpPtfaixlMgcW00CIZEpmn5
#      - CLOUD_NAME=dyamr9ym3
#      - CLOUD_API_KEY=385269193982147
#      - CLOUD_API_SECRET=-h9hU43QMy68AcIaMyP0ULKbibI
#      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
#      - ELASTIC_APM_SERVER_URL=http://apm_server_container:8200
#      - ELASTIC_APM_SECRET_TOKEN=
#    depends_on:
#      - elasticsearch
#      - mongodb
  
networks:
  elastic:
    name: elastic
