apiVersion: v1
kind: Service
metadata:
  name: market-mysql
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: market-mysql
  ports:
  - name: market-mysql
    port: 3306
    targetPort: 3306