apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-notification
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market-notification
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25% 
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: market-notification
    spec:
      containers:
      - name: market-notification
        image: eng9/marketplace-notification:stable
        imagePullPolicy: Always
        resources:
          limits:
            cpu: '0.5'
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 150Mi
        ports:
        - name: notification
          containerPort: 4001
        env:
          - name: ENABLE_APM
            value: '1'
          - name: NODE_ENV
            value: 'production'
          - name: CLIENT_URL
            value: 'http://localhost:3000'
          - name: RABBITMQ_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: market-backend-secret
                key: market-rabbitmq-endpoint
          - name: SENDER_EMAIL
            valueFrom:
              secretKeyRef:
                name: market-backend-secret
                key: sender-email
          - name: SENDER_EMAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: market-backend-secret
                key: sender-email-password
          - name: ELASTIC_SEARCH_URL
            valueFrom:
              secretKeyRef:
                name: market-backend-secret
                key: market-elasticsearch-url
          - name: ELASTIC_APM_SERVER_URL
            valueFrom:
              secretKeyRef:
                name: market-backend-secret
                key:  market-elastic-apm-server-url
          - name: ELASTIC_APM_SECRET_TOKEN
            valueFrom:
              secretKeyRef:
                name: market-backend-secret
                key: market-elastic-apm-secret-token