apiVersion: v1
kind: Service
metadata:
  name: market-notification
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: market-notification
  ports:
  - name: notification
    port: 4001
    targetPort: 4001
    protocol: TCP