apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-queue
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market-queue
  template:
    metadata:
      labels:
        app: market-queue
    spec:
      containers:
      - name: market-queue
        image: rabbitmq:3.12.8-management-alpine
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: market-backend-secret
              key: market-rabbitmq-user
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: market-backend-secret
              key: market-rabbitmq-password
        resources:
          limits:
            memory: "1Gi"
            cpu: "0.5"
          requests:
            memory: "150Mi"
            cpu: 100m
        ports:
        - name: queue
          containerPort: 5672
          protocol: TCP
        - name: mgmt
          containerPort: 15672
          protocol: TCP
        volumeMounts:
          - name: market-queue-storage
            mountPath: /var/lib/rabbitmq
      volumes:
        - name: market-queue-storage
          persistentVolumeClaim:
            claimName: rabbitmq-pvc