apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-kibana
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market-kibana
  template:
    metadata:
      labels:
        app: market-kibana
    spec:
      containers:
        - name: market-kibana
          image: docker.elastic.co/kibana/kibana:8.13.0
          resources:
            limits:
              memory: "1Gi"
              cpu: "1500m"
            requests:
              cpu: 250m
              memory: 1Gi
          ports:
          - name: market-kibana
            containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              # http://<service-name>.<namespace>.svc.cluster.local:<port-number>
              value: http://market-elastic.production.svc.cluster.local:9200
            - name: ELASTICSEARCH_USERNAME
              value: kibana_system
            - name: ELASTICSEARCH_PASSWORD
              # add to secret file
              value: kibana
            - name: ELASTICSEARCH_SERVICEACCOUNT_TOKEN
              value: AAEAAWVsYXN0aWMva2liYW5hL21hcmtldC1raWJhbmEyOnl1SGoyU29nU2lLLUVtSTBjSXR6Ync
          volumeMounts:
            - name: kibana-config
              mountPath: /usr/share/kibana/config
      volumes:
      - name: kibana-config
        configMap:
          name: kibana-config