apiVersion: v1
kind: Service
metadata:
  name: market-kibana
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: market-kibana
  ports:
  - name: market-kibana
    port: 5601
    targetPort: 5601
    protocol: TCP