apiVersion: v1
kind: Service
metadata:
  name: market-mongo
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: market-mongo
  ports:
  - name: market-mongo
    port: 27017
    targetPort: 27017