apiVersion: v1
kind: Service
metadata:
  name: market-postgres
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: market-postgres
  ports:
  - name: market-postgres
    port: 5432
    targetPort: 5432