apiVersion: v1
kind: Service
metadata:
  name:  market-redis
  namespace: production
spec:
  type:  ClusterIP
  selector:
    app: market-redis
  ports:
  - name:  market-redis
    port:  6379
    targetPort:  6379